[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#52796F"
backgroundColor = "#CAD2C5"
secondaryBackgroundColor = "#84A98C"
textColor = "#2F3E46"
font = "sans-serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"
